# Generated by Django 2.2.2 on 2019-07-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='sut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Student'),
        ),
    ]
